services:
  postgres:
    image: postgres:18.1
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql
    ports:
      - "${POSTGRES_PORT}:5432"
    
  databasus:
    image: databasus:v2.18.6
    container_name: databasus
    restart: unless-stopped
    volumes:
      - ./databasus-data:/databasus-data
    ports:
      - "${DATABASUS_PORT}:4005"
