services:
  postgres:
    image: postgres:18.1
    container_name: infra-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - infra-postgres-data:/var/lib/postgresql
    ports:
      - "${POSTGRES_PORT}:5432"
    
  databasus:
    image: databasus/databasus:v2.18.6
    container_name: infra-databasus
    restart: unless-stopped
    volumes:
      - infra-databasus-data:/databasus-data
    ports:
      - "${DATABASUS_PORT}:4005"

  redis:
    image: redis:8.4.0
    container_name: infra-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes", "--bind", "0.0.0.0", "--protected-mode", "no", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - infra-redis-data:/data
    ports:
      - "${REDIS_PORT}:6379"

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: infra-minio
    restart: unless-stopped
    command: ["server", "/data", "--console-address", ":9001"]
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - infra-minio-data:/data
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"

volumes:
  infra-postgres-data:
  infra-databasus-data:
  infra-redis-data:
  infra-minio-data:
