services:
  postgres:
    image: postgres:18.1
    container_name: infra-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - infra-postgres-data:/var/lib/postgresql
    ports:
      - "${POSTGRES_PORT}:5432"
    
  databasus:
    image: databasus/databasus:v2.18.6
    container_name: infra-databasus
    restart: unless-stopped
    volumes:
      - infra-databasus-data:/databasus-data
    ports:
      - "${DATABASUS_PORT}:4005"

  redis:
    image: redis:8.4.0
    container_name: infra-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - infra-redis-data:/data
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  infra-postgres-data:
  infra-databasus-data:
  infra-redis-data:
